locallibrary/catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView
from django.conf.urls import include

urlpatterns = [
	
	path('', views.index, name='index'),
	
	path('construction/', views.construction, name='under_construction'),



]

urlpatterns += [

	path('keys/', views.KeyListView.as_view(), name='keys'),

	path('key/<int:pk>/detail', views.KeyDetailView.as_view(), name='roomkey-detail'),

	path('key/<int:pk>/request', views.KeyRequestCreate.as_view(), name='roomkey-request'),

	path('mykeys/', views.LoanedKeysByUserListView.as_view(), name='borrowed-keys'),

	path('key/<uuid:pk>/renew/', views.renew_key_user, name='renew-key-user'),

	path('borrowedKeys/', views.LoanedKeysAllListView.as_view(), name='all-borrowed-keys'),

	path('key/agreement', views.KeyAgreement, name='key-agreement'),

	path('keys/all-requests', views.KeyRequestListView.as_view(), name='all-requested-keys'),

	path('keys/request/<int:pk>', views.KeyRequestDetailView.as_view(), name='key-request-detail'),

	path('keys/request/<int:pk>/update', views.KeyRequestUpdate.as_view(), name='key-request-update'),

]

urlpatterns += [

	path('maintenance/', views.MaintenanceListView.as_view(), name='maintenance-home'),

	path('maintenance-wip/', views.MaintenanceRequestListView.as_view(), name='wip-maintenance'),

	path('maintenance/<int:pk>', views.MaintenanceRequestDetailView.as_view(), name='maintenancerequest-detail'),

	path('maintenance-completed/', views.CompletedMaintenanceListView.as_view(), name='completed-maintenance'),

	path('maintenance/create/', views.MaintenanceRequestCreate.as_view(), name='maintenance_create'),

	path('maintenance/<int:pk>/update/', views.MaintenanceRequestUpdate.as_view(), name='maintenancerequest_update'),

]

urlpatterns += [

	path('move-request/', views.MoveRequestListView.as_view(), name='move-home'),


]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] +static(settings.STATIC_URL, document_roots=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User
from datetime import date
import uuid # Required for unique book instances

# Create your models here.

class RoomKey(models.Model):
    """
    Model representing rooms
    """
    room_name = models.CharField(max_length=100, help_text="Enter the name of the key.", verbose_name="Door #")
    room_des = models.CharField(max_length=200, help_text="Give a brief description of the key", verbose_name="Room description")
    key_symb = models.CharField(max_length=10, help_text="Enter the keyset symbol", verbose_name="Keyset Symbol", null=True, blank=True)
    bitting_num = models.PositiveIntegerField(help_text="Enter the bitting number (max length 10)", verbose_name="Bitting #", null=True, blank=True)

    OFFICE_LOCATION = (
        ('k', 'Kitchener'),
        ('h', 'Hamilton'),
    )
    
    office = models.CharField(max_length=1, choices=OFFICE_LOCATION, default='k', help_text='')

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('roomkey-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}'.format(self.room_name)

class KeyInstance(models.Model):
    """
    Model representing key instances.
    """
    roomkey = models.ForeignKey('RoomKey',verbose_name="Room", on_delete=models.SET_NULL, null=True) 
    keyrequest = models.OneToOneField('KeyRequest', verbose_name='Key requests', on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('a', 'Available'),
        ('o', 'On loan'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, help_text='Key availability', verbose_name="Key status", blank=True)

    date_out = models.DateField(null=True, blank=True, verbose_name="Date Issued")
    date_in = models.DateField(null=True, blank=True, verbose_name="Date to be returned")
    
    key_notes = models.CharField(max_length=2000, help_text='Key instance notes if applicable', null=True, blank=True)

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular key")

    class Meta:
        ordering = ["date_in"]


    def is_overdue(self):
        if self.date_in and date.today() > self.date_in:
            return True
        return False
    
    def __str__(self):
        """
        String for representing the Model object
        """
        return '{1} ({0})'.format(self.id,self.roomkey.room_name)

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('keys')

class KeyRequest(models.Model):
    """
    Model that will hold the key requests
    """
    roomkey = models.ForeignKey('RoomKey',verbose_name="Room", on_delete=models.SET_NULL, null=True) 

    requester = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Requested by')
    
    # borrower is ther person who has the key
    borrower = models.CharField(max_length=100, help_text='Enter the full name of the person who will be responsible for the key')

    REQUEST_STATUS = (
        ('p', 'Pending'),
        ('a', 'Approved'),
        ('d', 'Denied'),
    )

    request_status = models.CharField(max_length=1, choices=REQUEST_STATUS, default='p', verbose_name='Request status', blank=True)

    date_requested = models.DateField(auto_now_add=True)
    date_completed = models.DateField(null=True, blank=True)
    
    request_comments =  models.TextField(max_length=2000, help_text='Enter a brief reason for the request')

    def __str__(self):
        """
        String for representing the Model object
        """
        return '{2}-{0} ({1})'.format(self.roomkey.room_name, self.date_requested, self.requester)

    def get_absolute_url(self):

        return reverse('key-request-detail', args=[str(self.id)])

class MaintenanceRequest(models.Model):
    """
    Model that will hold the maintenance requests
    """
    requester = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Requested by')
    
    OFFICE_LOCATION = (
        ('k', 'Kitchener'),
        ('h', 'Hamilton'),
    )
    
    office = models.CharField(max_length=1, choices=OFFICE_LOCATION, default='k', help_text='')

    UG_LEVEL = (
        ('2', 'Low'),
        ('1', 'Medium'),
        ('0', 'High'),
    )

    urgency = models.CharField(max_length=1, choices=UG_LEVEL, default='2')

    REQUEST_STATUS = (
        ('s', 'Submitted'),
        ('w', 'Work in Progress'),
        ('c', 'Completed'),
    )

    status = models.CharField(max_length=1, choices=REQUEST_STATUS, blank=True, default='s', help_text='') 

    date_submitted = models.DateField(auto_now_add=True)
    date_completed = models.DateField(null=True, blank=True)
    request_comments =  models.TextField(max_length=2000, help_text='Enter a brief description of the request')

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('maintenancerequest-detail', args=[str(self.id)])

    def get_compcount(self):
        return MaintenanceRequest.objects.filter(status__exact='c').count()

    def get_pendcount(self):
        return MaintenanceRequest.objects.exclude(status__exact='c').count()

class MoveRequest(models.Model):
    """
    Model that will hold move requests
    """
    move_person = models.CharField(max_length=40)
    move_to = models.CharField(max_length=100)
    move_date = models.DateField(help_text='Enter the proposed date of move')
    move_conditions = models.CharField(max_length=2000, null=True, blank=True)
    requested_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


# ===================================================================================================

locallibrary/catalog/views.py
from django.shortcuts import render, redirect
from .models import *
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
import datetime
from .forms import *
from django.shortcuts import render_to_response
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms.formsets import formset_factory



# Create your views here.

def index(request):
	"""
	View function for home page of site.
	"""
	
	# Render the HTML template index.html with the data in the context variable
	return render(
		request,
		'index.html',
	)
def construction(request):
 
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'under_construction.html',
    )


def KeyAgreement(request):

    return render(
        request,
        'catalog/roomkey_agreement.html',
    )
# ===================================== KEYS ====================================================

class KeyListView(generic.ListView):
    model = RoomKey
    fields = '__all__'
    template_name = 'catalog/roomkey_list.html'

    
class KeyDetailView(generic.DetailView):
    model = RoomKey

# view for making a key request
class KeyRequestCreate(CreateView):
    model = KeyRequest
    fields = ['roomkey', 'requester', 'borrower', 'request_comments']
    template_name = 'catalog/roomkey_request_form.html'

class KeyAgreement111(CreateView):
    model = KeyRequest
    fields = ['roomkey', 'requester', 'borrower', 'request_comments']
    template_name = 'catalog/roomkey_agreement.html'

class LoanedKeysByUserListView(LoginRequiredMixin,generic.ListView):
    model = KeyInstance
    template_name = 'catalog/roomkey_list_borrowed_user.html'

    def get_queryset(self):
        return KeyInstance.objects.filter(requester=self.request.user).filter(status__exact='o').order_by('date_out')

class LoanedKeysAllListView(PermissionRequiredMixin,generic.ListView):
    
    model = KeyInstance
    permission_required = 'catalog.can_mark_returned'
    template_name ='catalog/roomkey-all-borrowed.html'
        
    def get_queryset(self):
        return KeyInstance.objects.filter(status__exact='o').order_by('date_in')  

class KeyRequestListView(PermissionRequiredMixin, generic.ListView):
    model = KeyRequest
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/roomkey_requests_all.html'

class KeyRequestUpdate(UpdateView):
    model = KeyRequest
    inline_model = KeyInstance
    fields = ['request_status', 'request_comments', ]
    # initial = {'date_in': datetime.date.today()}
    template_name = 'catalog/roomkey_request_form.html'

class KeyRequestDetailView(generic.DetailView):
    model = KeyRequest
    template_name = "catalog/roomkey_request_detail.html"

    def RequestDetail(request):
        num_keyinstances_available = KeyInstance.objects.filter(status__exact='a').count()

        return render(
            request,
            'key-request-detail',
            context = {'num_key_available':num_keyinstances_available},
        )
        
@permission_required('catalog.can_mark_returned')
def renew_key_user(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    key_inst=get_object_or_404(KeyInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewKeyForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            key_inst.date_in = form.cleaned_data['renewal_date']
            key_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed-keys') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewKeyForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/roomkey_renew_user.html', {'form': form, 'keyinst':key_inst})

def add_poll(request):
    if request.POST():
        keyinst_valid = KeyInstanceForm.is_valid()
        keyreq_valid = KeyRequestForm.is_valid()

        # we do this since 'and' short circuits and we want to check to whole page for form errors
        if keyinst_valid and keyreq_valid:
            KeyInstance = KeyInstanceForm.save()
            KeyRequest = KeyRequestForm.save(commit=False)  
       
            return HttpResponseRedirect('all-requested-keys')


# =================================== MAINTENANCE REQUESTS=============================================================
# view for maintenance home page
class MaintenanceListView(generic.ListView):
    model = MaintenanceRequest
    template_name = 'catalog/maintenance-home.html'

# view for pending maintenance requests
class MaintenanceRequestListView(LoginRequiredMixin,generic.ListView):
    model = MaintenanceRequest
    template_name = 'catalog/maintenancerequest_list.html'

    def get_queryset(self):
        return MaintenanceRequest.objects.order_by('urgency', 'status')

# view for completed maintenance requests
class CompletedMaintenanceListView(LoginRequiredMixin,generic.ListView):
    model = MaintenanceRequest
    template_name = 'catalog/maintenance_list_completed.html'

    def get_queryset(self):
        return MaintenanceRequest.objects.filter(status__exact='c').order_by('-date_completed')

# view for individual maintenance request details
class MaintenanceRequestDetailView(generic.DetailView):
    model = MaintenanceRequest

# view for creating maintenacne request
class MaintenanceRequestCreate(CreateView):
    model = MaintenanceRequest
    fields = ['requester', 'office', 'urgency', 'status', 'request_comments']

class MaintenanceRequestUpdate(UpdateView):
    model = MaintenanceRequest
    fields = ['status', 'date_completed', 'request_comments']
    initial = {'date_completed': datetime.date.today()}




# =========================================MOVE REQUESTS=========================================================
class MoveRequestListView(generic.ListView):
    model = MoveRequest
    template_name = 'catalog/move-home.html'


def move_request(request):

    MoveFormSet = formset_factory(MoveForm, formset=BaseMoveFormSet)

    if request.method == 'POST':
        move_formset = BaseMoveFormSet(request.POST)

locallibrary/catalog/templates/catalog/maintenance_list_completed.html
{% extends "base_generic.html" %}

{% block content %}
  
<div class="container maintenance-container">
  
  <div class="row" >
    <div class="maintenance-title" ">
      <h1 class="mainrow">COMPLETE</h1>
      <h4 class="maintenance-under">View and submit all maintenance requests here</h4>
    </div>
  </div>

  <div class="row">
    {% if maintenancerequest_list %}
    <div class="col-lg-12">
      <table class="table table-hover maintenance-tables bgreen">
      <thead>
        <tr>
          <th>Status</th>
          <th>Date Completed</th>
          <th>Urgency</th>
          <th>Location</th>
          <th>Date Submitted</th>
          <th>Comments</th>
          <th>Request by</th>
          <th>Details</th>
        </tr>
      </thead>

      {% for request in maintenancerequest_list %}
      {% if request.status == 'c' %}
       
      <tr>
          <td>{{ request.get_status_display }}</td>
          <td>{{ request.date_completed }}</td>
          <td>{{ request.get_urgency_display }}</td>
          <td>{{ request.get_office_display }}</td>
          <td>{{ request.date_submitted }}</td>
          <td>{{ request.request_comments|truncatechars:38 }}</td>
          <td>{{ request.requester }}</td>  
          <td><a href="{{ request.get_absolute_url }}">See more</a></td>   
      </tr>
       
      {% endif %}
      {% endfor %}

     </table>
    </div>
    

    
    {% else %}
      <div class="col-lg-12">
        <div class="mainpanelcontent">
           <h4>There are no completed maintenance requests</h4>
        </div>
         
      </div>
  
    {% endif %} 

  </div>

</div>
{% endblock %}

locallibrary/catalog/templates/catalog/maintenancerequest_detail.html
{% extends "base_generic.html" %}

{% block content %}

<div class="container maintenance-container">
	

	<div class="row" >
		<div class="maintenance-title" ">
			<h1 class="mainrow">MAINTENANCE</h1>
			<h4 class="maintenance-under2">View and submit all maintenance requests here</h4>
		</div>
	</div>


	<div class="row">
		<div class="mainpanel col-lg-12">
			<div class="mainpanelcontent bdblue">
				<div class="content-title">
					<h3>Request #{{ maintenancerequest.pk }}</h3>
				</div>
				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Status &nbsp;</h4>
					</div>
					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.get_status_display }}</p>
					</div>
				</div>

				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Urgency &nbsp;</h4>
					</div>
					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.get_urgency_display }}</p>
					</div>
				</div>
				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Location &nbsp;</h4>
					</div>
					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.get_office_display }}</p>
					</div>
				</div>
				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Last Updated &nbsp;</h4>
					</div>
					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.date_completed }}</p>
					</div>
				</div>
				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Date Submitted &nbsp;</h4>
					</div>
					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.date_submitted }}</p>
					</div>
				</div>
				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Requested by &nbsp;</h4>
					</div>
					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.requester }}</p>
					</div>
				</div>
				<div class="container-inline mainpanelcontent">
					<div class="col-lg-4">
						<h4>Request Details &nbsp;</h4>
					</div>

					<div class="col-lg-6">
						<p class="maintenance-under2">{{ maintenancerequest.request_comments }}</>
					</div>
				</div>
				
				<div class="container-inline mainpanelcontent" >
					<div class="col-lg-2 page-button ">
						<a href="{% url 'maintenancerequest_update' maintenancerequest.pk %}" class="maintenance-link"><h4>Update</h4></a>
					</div>
					<div class="col-lg-10"></div>
				</div>
			</div>
		</div>
	</div>

</div>


{% endblock %}

locallibrary/catalog/templates/catalog/maintenancerequest_list.html
{% extends "base_generic.html" %}

{% block content %}

<div class="container maintenance-container">
  

  <div class="row" >
    <div class="maintenance-title">
      <h1 class="mainrow">PENDING</h1>
      <h4 class="maintenance-under">View and submit all maintenance requests here</h4>
    </div>
  </div>

  <div class="row">
      {% if maintenancerequest_list %}
      <div class="col-lg-12">
        <table class="table table-hover maintenance-tables bblue">
        <thead>
          <tr>
            <th>Status</th>
            <th>Last Updated</th>
            <th>Urgency</th>
            <th>Location</th>
            <th>Date Submitted</th>
            <th>Comments</th>
            <th>Request by</th>
            <th>Details</th>
          </tr>
        </thead>

        {% for request in maintenancerequest_list %}
        {% if request.status != 'c' %}
         
        <tr>
            <td>{{ request.get_status_display }}</td>
            <td>{{ request.date_completed }}</td>
            <td>{{ request.get_urgency_display }}</td>
            <td>{{ request.get_office_display }}</td>
            <td>{{ request.date_submitted }}</td>
            <td>{{ request.request_comments|truncatechars:50 }}</td>
            <td>{{ request.requester }}</td>  
            <td><a href="{{ request.get_absolute_url }}">See more</a></td>   
        </tr>
         
        {% endif %}
        {% endfor %}

       </table>
      </div>
      

      
      {% else %}
        <div class="col-lg-12">
          <div class="mainpanelcontent">
             <h4>There are no incomplete maintenance requests</h4>
          </div>
           
        </div>
    
      {% endif %} 

  </div>
</div>
{% endblock %}

locallibrary/catalog/templates/catalog/roomkey-all-borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Keys</h1>

    {% if keyinstance_list %}
    <ul>

      {% for keyinst in keyinstance_list %} 
      <li class="{% if keyinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'roomkey-detail' keyinst.roomkey.pk %}">{{keyinst.roomkey}}</a> ({{ keyinst.date_in }}) {% if user.is_staff %}- {{ keyinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew_key_user' keyinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no keys borrowed.</p>
    {% endif %}  
         
{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_agreement.html
{% extends "base_generic.html" %}

{% block content %}
<h3>Key Holder's Agreement</h3>

<p>I  <b>{{ user.get_username }}</b> acknowledge receipt of the keys designated above and agree to the following terms.</p>

<p>1. The key described herein remains the property of WalterFedy/AEC Developments</p>
 
<p>2. The key is entrusted to me for my exclusive use. I will not duplicate, loan, transfer, exchange, misuse, modify, alter, or otherwise allow its use or possession by any other person</p>
 
<p>3. I will report its loss, theft, or destruction immediately to my department</p>
 
<p>4. If this key becomes lost, stolen, or not available for return, I will pay the key replacement charge</p>
 
<p>5. Upon employment termination or request from team leader, I will return the key promptly, in person, and only to operations</p>

<p>Signed by: <b>{{ user.get_username }}</b>

<p>Date: {% now "jS F Y H:i" %}</p>



{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ roomkey.room_name }}</h1>

  <p><strong>Description:</strong> {{ roomkey.room_des }}</p>
  <p><strong>Number of Keys:</strong> {{ roomkey.keyinstance_set.all.count }}</p> 
  
  <div style="margin-left:20px;margin-top:20px">
    
    <button type='button' class='btn-lg'><a href="{% url 'roomkey-request' roomkey.pk %}">Request</a></button>


    <h4>Copies</h4>
    

   <div>
    {% if roomkey.keyinstance_set.all %}
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Room Key</th>
          <th>Borrower</th>
          <th>Status</th>
          <th>Date Out</th>
          <th>Date In</th>
          <th>Key ID</th>
        </tr>
      </thead>

      {% for copy in roomkey.keyinstance_set.all %}
     
      <tr>
          <td>{{ copy.roomkey }} {{ forloop.counter }}</td>
          <td>{{ copy.keyrequest.borrower }}</td>
          <td>{{ copy.get_status_display }}</td>
          <td>{{ copy.date_out }}</td>
          <td>{{ copy.date_in }}</td>
          <td>{{ copy.id }}</td>
      </tr>
       
 
      {% endfor %}

      </table>

    
    {% else %}
      <p>There are no keys for this room.</p>
    {% endif %} 
  </div>

  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_list.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="content-title">
      <h1>Key List</h1>
  </div>
   
  <div class="split" style="width: 600px">
    <div class = 'centered'>
        <h3>INTSRUCTINOS ON HOW TO CHECK OUT A KEY</h3>
    </div>
   </div>

    <div class="split">
    <div class = 'centered'>
    {% if roomkey_list %}
    <div class="vertical-menu">

      {% for roomkey in roomkey_list %}

        <a href="{{ roomkey.get_absolute_url }}">{{ roomkey.room_name }} ({{ roomkey.room_des }}) - Keys: {{ roomkey.keyinstance_set.all.count }}</a>

      {% endfor %}

    </div>
    {% else %}
      <p>There are no keys in the library.</p>
    {% endif %}
    </div>
   </div>
    
{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Borrowed keys</h1>

	{% if keyinstance_list %}
	<ul>
		{% for roomkey in keyinstance_list %}
			<li>
				<a href="{% url 'roomkey-detail' roomkey.roomkey.pk %}">{{ roomkey.roomkey }}</a> ({{ roomkey.date_in }}) - {{ roomkey.id }}
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no keys borrowed.</p>
	{% endif %}	

{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_renew_user.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{keyinst.roomkey}}</h1>
    <p>Borrower: {{keyinst.borrower}}</p>
    <p{% if keyinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{keyinst.date_in}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_request_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Key Request #{{ keyrequest.pk }}</h1>

<p>Request for: {{ keyrequest.roomkey }}</p>
<p>Available keys: </p>

<br>
	
<p>Requested by: {{ keyrequest.requester }}</p>

<p>Borrower: {{ keyrequest.borrower }}</p>

<p>Request Status: {{ keyrequest.get_request_status_display }}</p>

<p>Date Requested: {{ keyrequest.date_requested }}</p>

<p>Request Comments: {{ keyrequest.request_comments }}</p>


<br>


<p>Assigned key: {{ keyrequest.keyinstance }}</p>

<p>Key Status: {{ keyrequest.keyinstance.get_status_display }}</p>

<p>Date Assigned: {{ keyrequest.keyinstance.date_in }}</p>

<p>Return Date: {{ keyrequest.keyinstance.date_out }}</p>

<div>
	<a href="{% url 'key-request-update' keyrequest.pk %}"><h4>Update</h4></a>
</div>

{% endblock %}

locallibrary/catalog/templates/catalog/roomkey_requests_all.html
{% extends "base_generic.html" %}

{% block content %}

 <div>
    {% if keyrequest_list %}
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Room</th>
          <th>Requester</th>
          <th>Borrower</th>
          <th>Status</th>
          <th>Date Requested</th>
          <th>Comments</th>
          <th>Details</th>
        </tr>
      </thead>

      {% for request in keyrequest_list %}
     
      <tr>
         <td>{{ request.roomkey }}</td>
         <td>{{ request.requester }}</td>
         <td>{{ request.borrower }}</td>
         <td>{{ request.get_request_status_display }}</td>
         <td>{{ request.date_requested }}</td>
         <td>{{ request.request_comments }}</td>
         <td><a href="{{ request.get_absolute_url }}">See more</a></td>
      </tr>
       
 
      {% endfor %}

      </table>

    
    {% else %}
      <p>There are key requests.</p>
    {% endif %} 
  </div>


{% endblock %}